### PR TITLE
Fixes #1508 and #1295 autosave files

### LINKED ISSUE #1508: Move autosave-files to a reboot-save location on Linux
Hi there,
when ganttproject crashes it is possible to recover unsaved changes due to the _ganttproject_autosaveXXX.gan files below /tmp . This is only usefull as long as the OS doesn't crash/reboot/runs out of battery.

When Linux starts, it will delete all files and folders below /tmp which includes ganttproject autosave-files. See [here](http://www.pathname.com/fhs/pub/fhs-2.3.html#TMPTEMPORARYFILES)

Probably /var/tmp would be a better choice, since files in this directory are *not* cleaned up after a reboot. See [here](http://www.pathname.com/fhs/pub/fhs-2.3.html#VARTMPTEMPORARYFILESPRESERVEDBETWEE).

On a side note (probably a new/different issue), it would be helpful, to check for autosave-files which are newer than the current one, when ganttproject opens a an existing project. I found it non-obvious to search for autosave-files after my system crashed the other day.

Thanks for the good work!

### PR DESCRIPTION
**Pull request by Anaitz98**
trying to solve the issue #1508 i  found that sometimes last accesed time is not changing so i  changed a little bit how it selects the files to delete.
modifiedTime

### CODE REVIEW

File: ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java [hunk 1]
```diff
@@ -255,7 +257,12 @@ private FileSystem getAutosaveZipFs() {
   }
 
   private static File getTempDir() {
-    File tempDir = new File(System.getProperty("java.io.tmpdir"));
+    File tempDir;
+    if (System.getProperty("os.name").toLowerCase().equals("linux")){
+      tempDir = new File("/var/tmp");
```
Comment (dbarashev) [inline ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java:262]: I understand the need, however, we must be careful when working with paths which come not from Java. `/var/tmp` may not exist, it may exist but be not writable, we may or may not  have permissions to create it if it does not exist. Linux sysadmins may want to use some other directory instead, which is not possible when the value is hardcoded. 

Also, I doubt that `os.name` is always exactly (lowercased) `linux` when running on Linux.
  
Perhaps, it makes more sense to check if such directory exists and is writable and use it in case of success, otherwise just use the default temporary file directory.

File: ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java [hunk 2]
```diff
@@ -207,7 +207,9 @@ public static Runnable createAutosaveCleanup() {
       GPLogger.log("Options file:" + optionsFile.getAbsolutePath());
       BasicFileAttributes attrs = Files.readAttributes(optionsFile.toPath(), BasicFileAttributes.class);
       FileTime accessTime = attrs.lastAccessTime();
-      cutoff = Math.min(accessTime.toMillis(), now);
+      FileTime modifyTime = attrs.lastModifiedTime();
+      long lastFileTime = Math.max(accessTime.toMillis(),modifyTime.toMillis());
```
Comment (dbarashev) [inline ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java:211]: please use spaces to separate function arguments.
```suggestion
      long lastFileTime = Math.max(accessTime.toMillis(), modifyTime.toMillis());
```

File: ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java [hunk 3]
```diff
@@ -191,7 +191,7 @@ public Document newDocument(String path) throws IOException {
 
   @Override
   public Document newAutosaveDocument() throws IOException {
-    File tempFile = File.createTempFile("_ganttproject_autosave", ".gan");
+    File tempFile = File.createTempFile("_ganttproject_autosave", ".gan",getTempDir());
```
Comment (dbarashev) [inline ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java:194]:
```suggestion
    File tempFile = File.createTempFile("_ganttproject_autosave", ".gan", getTempDir());
```

File: ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java (hunk 1 above)
Comment (Anaitz98) [reply ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java:262]: You mean not checking if OS is linux and just check if /var/tmp exists and its writable?

Or doing it once checked if OS its linux or not, mabe using SystemUtils.IS_OS_LINUX instead of os.name

Comment (dbarashev) [reply ganttproject/src/net/sourceforge/ganttproject/document/DocumentCreator.java:262]: I though about not checking, but perhaps SystemUtils + /var/tmp exists+is writable test is better.
